kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
     global:
       smtp_auth_username: AKIARIGS3TDHDHIRKBDID4TH3Nsada
       smtp_auth_password: BPrZcaGNZHWPqXZIgdGHDAGK,bvTTgNA7f/JOjmkexHguVVWfoUm8P
       smtp_require_tls: yes
       smtp_smarthost: email-smtp.us-east-1.amazontest.com:587
       smtp_from: infrasupport@test.com (test--Alerts)
     route:
       group_by: ['alertname', 'Project','instance', 'severity', 'Environment', 'Name', 'subject', 'job', 'nodename']
       group_wait: 30s
       group_interval: 5m
       repeat_interval: 30m
       receiver: Infrasupport
     receivers:
     - name: 'Infrasupport'
       email_configs:
       - to: 'kunal.jha@test.com'
